### ISSUE TITLE
Scorecard updates for 11/30

### ISSUE THREAD

**Issue by james-minton** [Hyperobjekt/spi-map#31]
- [x] Make these colored dots bigger. They are presently 8px circles; let's try 12px.

<img width="147" alt="Screen Shot 2022-11-14 at 12 48 01 PM" src="https://user-images.githubusercontent.com/33635008/201730429-eef6135e-3c54-4de4-ae06-73ad9381663a.png">

- [x] Add a (?) icon next to the indicators (e.g. "food insecurity rate") which triggers tooltip that expresses "definition" and "source." 

- This same tooltip is present on the map, when you select "show all indicators" and the list of indicators to choose from opens—except it doesn't show the source, and I think it should (e.g. _Source: American Community Survey 5-Year Data_). 
- **Definition** comes from items prefixed with `DESC_` in `en.json`; **source** comes from `source` in `metrics.json`.
- Also, they don't want us linking to the source, even though we have the links in `metrics.json`. They just want us to report the source without links to it.

- [x] Include legend on scorecard for colored circles

Provisional mockup, needs client approval (see upper left corner):

<img width="1163" alt="Screen Shot 2022-11-14 at 1 47 50 PM" src="https://user-images.githubusercontent.com/33635008/201777018-aff1b8a3-8f1e-4a2f-9154-fd183f079e8c.png">

**Comment by cfhull** [comment]
How does this look? 
![image](https://user-images.githubusercontent.com/5115526/201987479-0c4ce392-4c81-4d21-a26e-39f32195b838.png)

**Comment by james-minton** [comment]
Looks great! In the tooltips I would just prepend "Source:" before the source, like

> Source: CDC 500 cities
