### ISSUE TITLE
Map updates for 11/30

### ISSUE THREAD

**Issue by james-minton** [Hyperobjekt/spi-map#32]
- [x] Only allow comparisons of cities to cities, states to states, and tracts to tracts

This has three parts:

1. remove the "auto change on zoom" feature so that users must select between states and cities
2. make the `font-size` for the geography selection dropdown larger - equivalent to ~14px
3. the list of user-selected locations (which is populated by searching or clicking on the map) should be specific to the level of geography that is active at any point (states/cities), with no crossover
<img width="336" alt="Screen Shot 2022-11-15 at 10 26 11 AM" src="https://user-images.githubusercontent.com/33635008/201961094-4c688519-f0d5-4de6-ae60-bea2d15c21a6.png">

- [x] Build in navigation to main SPI Us Social Map site -- https://www.socialprogress.org/us
- [x] Remove Washington DC as a state.

I believe it's showing up as a state because it's in state-level data as well as cities. Chris, should I re-run the ETL with DC's row omitted, or is there another front end option? (ETL is a pain to run but I can do it if that's best.)

- [x] Add copyright notation at Mapbox attribution area at the bottom right of the app -- " Copyright © Social Progress Imperative, 2022"

**Comment by cfhull** [comment]
I don't think there's anything I can do in this repo to hide it. It might be easier + better, in the long run, to remove it from the source data.

**Comment by james-minton** [comment]
Fair enough! I think I'll rerun the data toward the end of this process just in case anything else comes up, so we can table the DC issue for now.

**Comment by cfhull** [comment]
@james-minton I updated the original comments "TBDs" based on the email discussion. (Logo link and copyright notice) I'll go ahead and implement them as well.

**Comment by james-minton** [comment]
Perfect!

**Comment by james-minton** [comment]
@cfhull re:

> the list of user-selected locations (which is populated by searching or clicking on the map) should be specific to the level of geography that is active at any point (states/cities), with no crossover

In [the dev deploy](https://development--spi-map.netlify.app/) I'm seeing this works, and it seems as though any stored locations are wiped out when changing the geography type. E.g. select states, click some and add them to the list, then switch to cities, click and add to the list, then back to states—states is empty.

It would be preferable for stored locations to persist when toggling back and forth between geography selections, though only for the currently selected type (states only lists states, etc.).
