### ISSUE TITLE
Add peer locations list to scorecard table

### ISSUE THREAD

**Issue by james-minton** [Hyperobjekt/spi-map#34]
- [ ] Add new row to scorecard at bottom listing the peer locations for each selected location. 
- [ ] Add new "Peer [cities/states]" jump-menu item in the left panel (conditional depending on geography type)

NOTE 11/21: ~~Data file has errors, sending back to client. Could begin work on UI meanwhile though.~~
NOTE 11/23: [Updated data file is here](https://docs.google.com/spreadsheets/d/1TOhFYs_RlrpW5ZDy_Pixp4x3S6k9ig-W/edit?usp=sharing&ouid=100970010941426875871&rtpof=true&sd=true). Apparently there are 16 peers now? Just a heads up.

**Comment by cfhull** [comment]
> Add new "Peer [cities/states]" jump-menu item in the left panel (conditional depending on geography type)

Can you elaborate more on what the requirement is for this?

**Comment by james-minton** [comment]
Sure @cfhull, just hoping to add another item to this menu that would scroll you down to peer locations. It should say Peer (Cities / States] depending on active location type.

<img width="315" alt="Screen Shot 2022-11-29 at 10 06 59 AM" src="https://user-images.githubusercontent.com/33635008/204565867-06f0304f-b0b1-403d-833e-2aa2eba9b7f0.png">

**Comment by cfhull** [comment]
Done and ready to review https://github.com/Hyperobjekt/spi-map/pull/35
