### ISSUE TITLE
6/2023 updates

### ISSUE THREAD

**Issue by james-minton** [Hyperobjekt/spi-map#51]
In the `tracts` branch, please do the following:

**Map view changes**

- [ ] reactivate auto-geography-change on zoom option. There used to be a toggle in the legend that enabled changing of regions depending on zoom level (e.g. geography selection would shift to tracts automatically if you zoom in far enough on cities). Client wanted it gone, now wants it back. I believe it was disabled in [this commit,](https://github.com/Hyperobjekt/spi-map/commit/db9de003258b5d43adfe59dafce717c08f27301c) so we just need to return that functionality.

**Scorecard changes**

(To get to the scorecard, select locations and click "view full data for locations" in the legend)

- [ ] remove "peer tracts" -- cut the bottom row in the scorecard, only for tracts (keep for cities/states)
<img width="585" alt="Screen Shot 2023-06-18 at 7 31 46 PM" src="https://github.com/Hyperobjekt/spi-map/assets/33635008/598ce8c0-a891-4f9d-9118-fe87697b0a67">

- [ ] Change “peer” language in upper left corner (just for tracts) to 
"Strengths and vulnerabilities of each census tract/neighborhood are relative to all census tracts/neighborhoods in that city."

<img width="358" alt="Screen Shot 2023-06-18 at 7 35 05 PM" src="https://github.com/Hyperobjekt/spi-map/assets/33635008/c7ff9409-aa5d-457d-803f-441e951b5d09">

- [ ] Data for the following indicators is not available for tracts. Remove rows for these indicators in the scorecard in tract view:

- Electricity generated by plants using renewable energy resources
- Overall water risk
- Drug overdose deaths
- Female representation in public office
- Disconnected youth
- State constitution against gender discrimination

Demographics:

- Below 200% Poverty Rate

---

These commits can be done in the `development` branch:

- [ ] In the scorecard view, when selecting a component or "Demographics" from the left side options, the scorecard moves to that section but cuts off the top of the heading text. Adjust the "scroll-to" functionality so this doesn't happen.

- [ ] In state and city view, when the "zoom to Hawaii" button is selected, the map is not centered and the menu covers the island. 
This is zooming to its current view because the state of Hawaii consists of many small islands to the west beyond the standard 8. (These are visible if you zoom in enough.) If we want to reduce the view to just the standard 8, we’ll need to use custom coordinates for the button or, e.g. Honolulu as the target.

**Comment by erbnando** [comment]
@james-minton,

Ok, here are `development` updates: https://github.com/Hyperobjekt/spi-map/pull/53
and here are `tracts` branch updates: https://github.com/Hyperobjekt/spi-map/pull/52

My only flag would be that here -- see below -- the font family of the hyperlinked text is different from the rest of the text.
<img src="https://github.com/Hyperobjekt/spi-map/assets/8950558/305a4667-5007-4513-98d0-e20ef6ca4263" width="400">

**Comment by james-minton** [comment]
Hey @erbnando, this is all great. Thanks! One small change: could you set "auto change on zoom" to be the default option on load?

**Comment by erbnando** [comment]
Hey @james-minton, that is the default setting for me on both mobile and desktop. Can you check again?
